name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y xorg-dev libx11-dev libxcb-keysyms1-dev libxkbcommon-dev libxkbcommon-x11-dev
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
