name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install pkg-config
        DEPS=$(grep -E '^\w+\s*[:+]?=' Makefile | sed -E 's/^.*pkg-config\s*--cflags\s*--libs\s*([^\s]+).*$$/\1/g' | tr '\n' ' ')
        sudo apt-get -y install $DEPS
    - name: make
      run: make
